ifndef::snippets[]
:snippets: ./build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4

= Problem API

== 문제 저장
=== 성공
operation::problem/save/success[snippets='request-fields,http-request,http-response']

=== 실패 : url 공백 오류
operation::problem/save/fail/emptyUrl[snippets='http-request,http-response']

=== 실패 : title(제목) 공백 오류
operation::problem/save/fail/emptyTitle[snippets='http-request,http-response']

=== 실패 : category(유형) 공백 오류
operation::problem/save/fail/emptyCategory[snippets='http-request,http-response']

=== 실패 : level(난이도) 공백 오류
operation::problem/save/fail/emptyLevel[snippets='http-request,http-response']

=== 실패 : 최저 level(난이도) 오류
operation::problem/save/fail/lowLevel[snippets='http-request,http-response']

=== 실패 : 최대 level(난이도) 오류
operation::problem/save/fail/highLevel[snippets='http-request,http-response']

== 문제 조회 : 단건
=== 성공
operation::problem/find/success[snippets='path-parameters,http-request,http-response']

== 문제 조회 : 가장 먼저 등록한 문제
=== 성공
operation::problem/pull/success[snippets='http-request,http-response']

== 문제 조회 : 목록
=== 성공
operation::problem/findAll/success[snippets='request-parameters,http-request,http-response']

== 문제 수정
=== 성공
operation::problem/update/success[snippets='path-parameters,request-fields,http-request,http-response']

=== 실패 : url 공백 오류
operation::problem/update/fail/emptyUrl[snippets='http-request,http-response']

=== 실패 : title(제목) 공백 오류
operation::problem/update/fail/emptyTitle[snippets='http-request,http-response']

=== 실패 : category(유형) 공백 오류
operation::problem/update/fail/emptyCategory[snippets='http-request,http-response']

=== 실패 : isSolved(풀이 여부) 공백 오류
operation::problem/update/fail/emptyIsSolved[snippets='http-request,http-response']

=== 실패 : level(난이도) 공백 오류
operation::problem/update/fail/emptyLevel[snippets='http-request,http-response']

=== 실패 : 최저 level(난이도) 오류
operation::problem/update/fail/lowLevel[snippets='http-request,http-response']

=== 실패 : 최대 level(난이도) 오류
operation::problem/update/fail/highLevel[snippets='http-request,http-response']

== 문제 삭제
=== 성공
operation::problem/delete/success[snippets='path-parameters,http-request,http-response']

== 문제 되돌리기
=== 성공
operation::problem/recovery/success[snippets='path-parameters,http-request,http-response']


